name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v4
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-33-1-do-0-sgp1-1751704911382

      - name: Apply Dev and Prod K8s manifests Test
        run: |
          set -e
          echo "Applying Dev manifests..."
          kubectl apply -f infra/k8s
          echo "Applying Prod manifests..."
          kubectl apply -f infra/k8s-prod
